# Generated by Django 5.1.5 on 2025-02-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_voter_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
